# Generated by Django 3.0.7 on 2020-06-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200619_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='urlimage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
