# Generated by Django 3.0.7 on 2020-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200810_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='article',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
